import type { Metadata } from "next";
import "./globals.css";
import { Bricolage_Grotesque } from 'next/font/google';
import localFont from 'next/font/local'
import Header from '../components/layout/Header'
import Footer from "@/components/layout/Footer";
import CircleCursor from "@/components/ui/CircleCursor";
import { CursorProvider } from '@/context/CursorContext';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bricolage',
  weight:'500'
});

const pretendard = localFont({
  src: [
    {
      path: '../public/fonts/Pretendard-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Pretendard-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${bricolage.variable} ${pretendard.variable}`}>
      <body>
        <CursorProvider>
            <CircleCursor />
            <Header/>
            <main>
              {children}
            </main>
            <Footer/>
        </CursorProvider>
      </body>
    </html>
  );
}
