import type { Metadata } from "next";
import "./globals.css";
import { Bricolage_Grotesque } from 'next/font/google';
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bricolage',
  weight:'500'
});

const pretendard = localFont({
  src: '../public/fonts/Pretendard-Regular.woff2',
  display: 'swap',
  variable: '--font-pretendard',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${bricolage.variable} ${pretendard.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
